export interface People {
  id: number
  name: string
  job: string
  company: string
  language: string
  year: number
}

export const people: People[] = [
  {
    id: 1,
    name: 'Austina Ashbrook',
    job: 'Tax Accountant',
    company: 'Brightdog',
    language: 'Zulu',
    year: 2016,
  },
  {
    id: 2,
    name: 'Elysee Francesch',
    job: 'Clinical Specialist',
    company: 'Jetwire',
    language: 'Luxembourgish',
    year: 2018,
  },
  {
    id: 3,
    name: 'Margalo Egalton',
    job: 'Internal Auditor',
    company: 'Quatz',
    language: 'Italian',
    year: 2010,
  },
  {
    id: 4,
    name: 'Taryn Trenear',
    job: 'Assistant Professor',
    company: 'Ailane',
    language: 'Georgian',
    year: 2015,
  },
  {
    id: 5,
    name: 'Temple Lauks',
    job: 'Human Resources Assistant II',
    company: 'Innojam',
    language: 'Japanese',
    year: 2013,
  },
  {
    id: 6,
    name: 'Britte Naulty',
    job: 'Automation Specialist II',
    company: 'Edgewire',
    language: 'Catalan',
    year: 2010,
  },
  {
    id: 7,
    name: "Nadiya O'Dwyer",
    job: 'Staff Accountant IV',
    company: 'Voonder',
    language: 'Bislama',
    year: 2013,
  },
  {
    id: 8,
    name: 'Nate Gosnoll',
    job: 'Financial Analyst',
    company: 'Mymm',
    language: 'Lao',
    year: 2010,
  },
  {
    id: 9,
    name: 'Archer MacCallum',
    job: 'Safety Technician I',
    company: 'Youopia',
    language: 'Dzongkha',
    year: 2016,
  },
  {
    id: 10,
    name: 'Brad Bresnen',
    job: 'Food Chemist',
    company: 'Tagchat',
    language: 'Maltese',
    year: 2010,
  },
  {
    id: 11,
    name: 'Yorke Izac',
    job: 'Account Representative II',
    company: 'Eayo',
    language: 'Gujarati',
    year: 2014,
  },
  {
    id: 12,
    name: 'Frannie Tarburn',
    job: 'Account Executive',
    company: 'Realbuzz',
    language: 'Kyrgyz',
    year: 2014,
  },
  {
    id: 13,
    name: 'Lilllie Nesey',
    job: 'Human Resources Assistant II',
    company: 'Buzzster',
    language: 'Korean',
    year: 2010,
  },
  {
    id: 14,
    name: 'Bartie Basil',
    job: 'Compensation Analyst',
    company: 'Tagtune',
    language: 'Polish',
    year: 2012,
  },
  {
    id: 15,
    name: "Raddy O'Dare",
    job: 'Senior Developer',
    company: 'Feednation',
    language: 'Lao',
    year: 2018,
  },
  {
    id: 16,
    name: 'Adolphe Duplock',
    job: 'Help Desk Technician',
    company: 'Yakitri',
    language: 'Irish Gaelic',
    year: 2020,
  },
  {
    id: 17,
    name: 'Teresita Arbon',
    job: 'Programmer Analyst IV',
    company: 'Wikizz',
    language: 'Albanian',
    year: 2013,
  },
  {
    id: 18,
    name: 'Kellen Lenaghen',
    job: 'Actuary',
    company: 'Pixope',
    language: 'Norwegian',
    year: 2012,
  },
  {
    id: 19,
    name: 'Janet Nozzolinii',
    job: 'Health Coach I',
    company: 'Zoombeat',
    language: 'Norwegian',
    year: 2020,
  },
  {
    id: 20,
    name: 'Baxie Foan',
    job: 'Administrative Assistant II',
    company: 'Twinte',
    language: 'Chinese',
    year: 2018,
  },
  {
    id: 21,
    name: 'Adolphus Bartoloma',
    job: 'Registered Nurse',
    company: 'Jamia',
    language: 'Macedonian',
    year: 2017,
  },
  {
    id: 22,
    name: 'Katalin Semeniuk',
    job: 'Computer Systems Analyst III',
    company: 'Devshare',
    language: 'Romanian',
    year: 2010,
  },
  {
    id: 23,
    name: 'Launce Iacovo',
    job: 'Clinical Specialist',
    company: 'Oloo',
    language: 'Norwegian',
    year: 2018,
  },
  {
    id: 24,
    name: 'Feodora Dalziell',
    job: 'Media Manager II',
    company: 'Rhyloo',
    language: 'Moldovan',
    year: 2014,
  },
  {
    id: 25,
    name: 'Vincenty Meddings',
    job: 'Accountant II',
    company: 'Viva',
    language: 'Greek',
    year: 2014,
  },
  {
    id: 26,
    name: 'Aloise Jurek',
    job: 'Paralegal',
    company: 'Devbug',
    language: 'Afrikaans',
    year: 2020,
  },
  {
    id: 27,
    name: 'Clementia Dangl',
    job: 'Administrative Assistant II',
    company: 'Yodel',
    language: 'Amharic',
    year: 2015,
  },
  {
    id: 28,
    name: 'Keelia Addy',
    job: 'Statistician II',
    company: 'Kazu',
    language: 'Dari',
    year: 2012,
  },
  {
    id: 29,
    name: 'Lemuel Rideout',
    job: 'Senior Cost Accountant',
    company: 'Mydeo',
    language: 'Japanese',
    year: 2018,
  },
  {
    id: 30,
    name: 'Yulma Spelwood',
    job: 'Compensation Analyst',
    company: 'Topdrive',
    language: 'Japanese',
    year: 2011,
  },
  {
    id: 31,
    name: 'Dara Cunnah',
    job: 'Senior Quality Engineer',
    company: 'Eamia',
    language: 'Chinese',
    year: 2017,
  },
  {
    id: 32,
    name: 'Charmion Peniman',
    job: 'Occupational Therapist',
    company: 'Photojam',
    language: 'Tok Pisin',
    year: 2011,
  },
  {
    id: 33,
    name: 'Reuven Stivani',
    job: 'Assistant Manager',
    company: 'Twimm',
    language: 'Belarusian',
    year: 2017,
  },
  {
    id: 34,
    name: 'Monah Chatan',
    job: 'Director of Sales',
    company: 'Viva',
    language: 'Tetum',
    year: 2019,
  },
  {
    id: 35,
    name: 'Betsy Tschiersch',
    job: 'Account Representative I',
    company: 'Gigabox',
    language: 'Luxembourgish',
    year: 2010,
  },
  {
    id: 36,
    name: 'Donn Lennarde',
    job: 'Senior Quality Engineer',
    company: 'Oyope',
    language: 'Finnish',
    year: 2016,
  },
  {
    id: 37,
    name: 'Molli Semorad',
    job: 'Project Manager',
    company: 'Twinte',
    language: 'Assamese',
    year: 2020,
  },
  {
    id: 38,
    name: 'Kittie Frain',
    job: 'Senior Financial Analyst',
    company: 'Jamia',
    language: 'Fijian',
    year: 2015,
  },
  {
    id: 39,
    name: 'Corri Badrock',
    job: 'Chemical Engineer',
    company: 'Quimm',
    language: 'Gujarati',
    year: 2014,
  },
  {
    id: 40,
    name: 'Darya Nutbeem',
    job: 'Staff Accountant IV',
    company: 'Zoovu',
    language: 'Tswana',
    year: 2015,
  },
  {
    id: 41,
    name: 'Thorpe Garthside',
    job: 'Research Associate',
    company: 'Zoomdog',
    language: 'Aymara',
    year: 2016,
  },
  {
    id: 42,
    name: 'Trina Jiggen',
    job: 'Senior Financial Analyst',
    company: 'Edgeify',
    language: 'Kashmiri',
    year: 2011,
  },
  {
    id: 43,
    name: 'Karrah Zanolli',
    job: 'Nurse',
    company: 'Midel',
    language: 'Papiamento',
    year: 2013,
  },
  {
    id: 44,
    name: 'Frances Annis',
    job: 'Senior Quality Engineer',
    company: 'Skyba',
    language: 'Nepali',
    year: 2012,
  },
  {
    id: 45,
    name: 'Giavani Minet',
    job: 'Marketing Assistant',
    company: 'Topiclounge',
    language: 'Swedish',
    year: 2014,
  },
  {
    id: 46,
    name: 'Meta Bertie',
    job: 'Programmer IV',
    company: 'Meezzy',
    language: 'Moldovan',
    year: 2010,
  },
  {
    id: 47,
    name: 'Yancey Trayford',
    job: 'Marketing Manager',
    company: 'Yotz',
    language: 'Portuguese',
    year: 2012,
  },
  {
    id: 48,
    name: 'Elna Ickowics',
    job: 'Engineer IV',
    company: 'Jaloo',
    language: 'German',
    year: 2019,
  },
  {
    id: 49,
    name: 'Therine Pischel',
    job: 'Web Designer II',
    company: 'Topicware',
    language: 'Amharic',
    year: 2016,
  },
  {
    id: 50,
    name: 'Wynnie Savidge',
    job: 'Research Associate',
    company: 'Meetz',
    language: 'Dutch',
    year: 2014,
  },
  {
    id: 51,
    name: 'Bobbi Scullin',
    job: 'Financial Analyst',
    company: 'Vimbo',
    language: 'Tetum',
    year: 2020,
  },
  {
    id: 52,
    name: "Adrianne O'Cannon",
    job: 'Clinical Specialist',
    company: 'Feedbug',
    language: 'Danish',
    year: 2012,
  },
  {
    id: 53,
    name: 'Cobby Dunning',
    job: 'Staff Scientist',
    company: 'Yoveo',
    language: 'Pashto',
    year: 2015,
  },
  {
    id: 54,
    name: 'Danna Martschik',
    job: 'Nurse',
    company: 'Avaveo',
    language: 'Zulu',
    year: 2012,
  },
  {
    id: 55,
    name: 'Shea Cotter',
    job: 'Research Associate',
    company: 'Vinte',
    language: 'Punjabi',
    year: 2014,
  },
  {
    id: 56,
    name: 'Elke Danby',
    job: 'VP Accounting',
    company: 'Bluejam',
    language: 'Guaraní',
    year: 2014,
  },
  {
    id: 57,
    name: 'Guinevere Cholwell',
    job: 'Research Nurse',
    company: 'Dabshots',
    language: 'Polish',
    year: 2020,
  },
  {
    id: 58,
    name: 'Christin Burtt',
    job: 'VP Quality Control',
    company: 'Kanoodle',
    language: 'Irish Gaelic',
    year: 2018,
  },
  {
    id: 59,
    name: 'Corri Grzegorek',
    job: 'VP Marketing',
    company: 'Voonder',
    language: 'Czech',
    year: 2010,
  },
  {
    id: 60,
    name: 'Romola Brain',
    job: 'Help Desk Technician',
    company: 'Yakidoo',
    language: 'Estonian',
    year: 2010,
  },
  {
    id: 61,
    name: 'Cally Enderlein',
    job: 'Software Test Engineer I',
    company: 'Realbuzz',
    language: 'Kyrgyz',
    year: 2010,
  },
  {
    id: 62,
    name: 'Correy Brim',
    job: 'Nuclear Power Engineer',
    company: 'Livetube',
    language: 'Tetum',
    year: 2013,
  },
  {
    id: 63,
    name: 'Aimee Spinige',
    job: 'Health Coach III',
    company: 'Bluejam',
    language: 'Armenian',
    year: 2020,
  },
  {
    id: 64,
    name: 'Ignacius Mandres',
    job: 'Junior Executive',
    company: 'Cogidoo',
    language: 'Bulgarian',
    year: 2018,
  },
  {
    id: 65,
    name: 'Justinn Souch',
    job: 'Physical Therapy Assistant',
    company: 'Mydo',
    language: 'Māori',
    year: 2015,
  },
  {
    id: 66,
    name: 'Cassie Paybody',
    job: 'Staff Accountant I',
    company: 'Riffpath',
    language: 'Telugu',
    year: 2017,
  },
  {
    id: 67,
    name: 'Timothee Lyman',
    job: 'Social Worker',
    company: 'Twitterlist',
    language: 'Irish Gaelic',
    year: 2011,
  },
  {
    id: 68,
    name: 'Atlante Lushey',
    job: 'Quality Control Specialist',
    company: 'Izio',
    language: 'Latvian',
    year: 2010,
  },
  {
    id: 69,
    name: 'Gavrielle Scemp',
    job: 'Quality Engineer',
    company: 'Oyoba',
    language: 'Catalan',
    year: 2012,
  },
  {
    id: 70,
    name: 'Doralynne Pulman',
    job: 'Structural Analysis Engineer',
    company: 'Plajo',
    language: 'Hiri Motu',
    year: 2013,
  },
  {
    id: 71,
    name: 'Kacy Longden',
    job: 'Sales Associate',
    company: 'Bluejam',
    language: 'Khmer',
    year: 2011,
  },
  {
    id: 72,
    name: 'Juline Wyles',
    job: 'Design Engineer',
    company: 'Trupe',
    language: 'Swahili',
    year: 2012,
  },
  {
    id: 73,
    name: 'Eamon Elsworth',
    job: 'Product Engineer',
    company: 'Yozio',
    language: 'Tamil',
    year: 2017,
  },
  {
    id: 74,
    name: 'Bastien Freschini',
    job: 'General Manager',
    company: 'Topicstorm',
    language: 'Malay',
    year: 2019,
  },
  {
    id: 75,
    name: 'Tessy Godbehere',
    job: 'Quality Engineer',
    company: 'Fivechat',
    language: 'Romanian',
    year: 2016,
  },
  {
    id: 76,
    name: 'Joela Foulks',
    job: 'Graphic Designer',
    company: 'Meevee',
    language: 'Malagasy',
    year: 2017,
  },
  {
    id: 77,
    name: 'Brett Bruniges',
    job: 'Database Administrator II',
    company: 'Edgetag',
    language: 'Luxembourgish',
    year: 2011,
  },
  {
    id: 78,
    name: 'Minnie Saffill',
    job: 'Administrative Assistant I',
    company: 'Kwinu',
    language: 'Estonian',
    year: 2015,
  },
  {
    id: 79,
    name: 'Gussy Roath',
    job: 'Marketing Assistant',
    company: 'Jabbersphere',
    language: 'Montenegrin',
    year: 2012,
  },
  {
    id: 80,
    name: 'Thorny Worrall',
    job: 'Environmental Tech',
    company: 'Kamba',
    language: 'Dzongkha',
    year: 2019,
  },
  {
    id: 81,
    name: 'Garland Summons',
    job: 'Civil Engineer',
    company: 'Browsezoom',
    language: 'Tsonga',
    year: 2016,
  },
  {
    id: 82,
    name: 'Carlina Muriel',
    job: 'Accounting Assistant I',
    company: 'Riffpedia',
    language: 'Mongolian',
    year: 2019,
  },
  {
    id: 83,
    name: 'Derrik Lundbeck',
    job: 'Assistant Media Planner',
    company: 'Ainyx',
    language: 'Dari',
    year: 2011,
  },
  {
    id: 84,
    name: 'Melita Elcom',
    job: 'Nuclear Power Engineer',
    company: 'Jaxbean',
    language: 'Dari',
    year: 2013,
  },
  {
    id: 85,
    name: 'Robinett Pendle',
    job: 'Senior Financial Analyst',
    company: 'Jazzy',
    language: 'Filipino',
    year: 2010,
  },
  {
    id: 86,
    name: 'Laina Dron',
    job: 'Director of Sales',
    company: 'Lazz',
    language: 'New Zealand Sign Language',
    year: 2019,
  },
  {
    id: 87,
    name: 'Yorgo Derisley',
    job: 'Occupational Therapist',
    company: 'Tazzy',
    language: 'Croatian',
    year: 2018,
  },
  {
    id: 88,
    name: 'Wynne Whistance',
    job: 'Research Nurse',
    company: 'Realfire',
    language: 'Filipino',
    year: 2019,
  },
  {
    id: 89,
    name: 'Wash Orwin',
    job: 'Senior Editor',
    company: 'Skynoodle',
    language: 'Zulu',
    year: 2011,
  },
  {
    id: 90,
    name: 'Sada Broker',
    job: 'Software Test Engineer III',
    company: 'Wikibox',
    language: 'Nepali',
    year: 2018,
  },
  {
    id: 91,
    name: 'Karilynn Milson',
    job: 'Cost Accountant',
    company: 'InnoZ',
    language: 'Bosnian',
    year: 2015,
  },
  {
    id: 92,
    name: 'Brandise Spenceley',
    job: 'General Manager',
    company: 'Katz',
    language: 'Norwegian',
    year: 2011,
  },
  {
    id: 93,
    name: 'Ula Walkowski',
    job: 'Registered Nurse',
    company: 'Yabox',
    language: 'Portuguese',
    year: 2011,
  },
  {
    id: 94,
    name: 'Obadiah Franklen',
    job: 'Professor',
    company: 'Thoughtstorm',
    language: 'Kyrgyz',
    year: 2015,
  },
  {
    id: 95,
    name: 'Quintina Feeney',
    job: 'Nurse',
    company: 'Kwimbee',
    language: 'Punjabi',
    year: 2015,
  },
  {
    id: 96,
    name: 'Leora Dicks',
    job: 'Nurse',
    company: 'Abata',
    language: 'Greek',
    year: 2011,
  },
  {
    id: 97,
    name: 'Adda Geertz',
    job: 'Nurse Practicioner',
    company: 'Leenti',
    language: 'Portuguese',
    year: 2011,
  },
  {
    id: 98,
    name: 'Martino MacConnulty',
    job: 'Accounting Assistant I',
    company: 'Babbleset',
    language: 'Lithuanian',
    year: 2019,
  },
  {
    id: 99,
    name: 'Theodora Vickery',
    job: 'Occupational Therapist',
    company: 'Trilia',
    language: 'Persian',
    year: 2020,
  },
  {
    id: 100,
    name: 'Arman Regelous',
    job: 'Statistician II',
    company: 'Shufflebeat',
    language: 'Northern Sotho',
    year: 2014,
  },
  {
    id: 101,
    name: 'Rad Sprionghall',
    job: 'Assistant Professor',
    company: 'Yambee',
    language: 'Persian',
    year: 2018,
  },
  {
    id: 102,
    name: 'Ashlee Kitlee',
    job: 'Chief Design Engineer',
    company: 'Topiczoom',
    language: 'Gujarati',
    year: 2014,
  },
  {
    id: 103,
    name: 'Jacynth Meak',
    job: 'General Manager',
    company: 'Photobean',
    language: 'Bosnian',
    year: 2020,
  },
  {
    id: 104,
    name: 'Rory Girdlestone',
    job: 'Accountant III',
    company: 'Jaxbean',
    language: 'Bislama',
    year: 2016,
  },
  {
    id: 105,
    name: 'Monika Fritzer',
    job: 'Social Worker',
    company: 'Twitterworks',
    language: 'Ndebele',
    year: 2012,
  },
  {
    id: 106,
    name: 'Francois Chishull',
    job: 'Financial Analyst',
    company: 'Yodel',
    language: 'Pashto',
    year: 2020,
  },
  {
    id: 107,
    name: 'Rosabella Easeman',
    job: 'Civil Engineer',
    company: 'Babbleblab',
    language: 'Tswana',
    year: 2020,
  },
  {
    id: 108,
    name: 'Von Pyrton',
    job: 'VP Accounting',
    company: 'Skibox',
    language: 'Dutch',
    year: 2010,
  },
  {
    id: 109,
    name: 'Cordey Breit',
    job: 'Compensation Analyst',
    company: 'Layo',
    language: 'Zulu',
    year: 2016,
  },
  {
    id: 110,
    name: 'Desiri Bottleson',
    job: 'Marketing Manager',
    company: 'Brainsphere',
    language: 'Pashto',
    year: 2016,
  },
]

export default people
